image:
  file: .gitpod.Dockerfile

tasks:
  - before: clear && echo 'Welcome to GuruShifu...'
    init: ./.ignore/init.sh
    command: ./.ignore/start.sh && cat .ignore/banner.txt

ports:
  - port: 3000
    onOpen: ignore
  - port: 8080
    onOpen: ignore
    visibility: public
  - port: 3306
    onOpen: ignore
    visibility: private

vscode:
  extensions:
    - k--kato.intellij-idea-keybindings
    - redhat.java